BMI_Calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("bmi-app/", include("bmi_app.urls", namespace="bmi_app")),
    path("useraccount-app/", include("useraccount_app.urls", namespace="useraccount_app")),
]

bmi_app/urls.py
from django.urls import path
from bmi_app.views import bmi_list, bmi_calculate, bmi_edit, bmi_delete, send_report

app_name = "bmi_app"

urlpatterns = [
    path("bmi-list/", bmi_list, name="bmi_list"),
    path("bmi-calculate/", bmi_calculate, name="bmi_calculate"),
    path("bmi-edit/<int:id>/", bmi_edit, name="bmi_edit"),
    path("bmi-delete/<int:id>/", bmi_delete, name="bmi_delete"),
    path("send_report/", send_report, name="send_report"),
]

bmi_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Suggestion(models.Model):
    BMI = (
        ("overweight","OVERWEIGHT"),
        ("obsessed","OBSESSED"),
        ("undeweight","UNDERWEIGHT"),
        ("normalweight","NORMALWEIGHT")
    )
    suggestion = models.CharField(max_length=255, choices=BMI)
    message = models.TextField()

    def __str__(self):
        return self.suggestion


class BMIMeasurement(models.Model):
    user = models.ForeignKey(User, related_name="bmi_app", on_delete=models.CASCADE, null=True)
    weight = models.FloatField()
    height = models.FloatField()
    bmi = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def bmi(self):
        return self.weight/self.height**2

    def __str__(self):
        return str(self.weight)

bmi_app/forms.py
from django import forms
from django.forms import widgets
from bmi_app.models import BMIMeasurement

class BmimeasuremantForm(forms.ModelForm):

    class Meta:
        model = BMIMeasurement
        # fields = [ "weight", "height",]
        fields = "__all__"
        exclude = ("user", )

    # def __init__(self, *args, **kwargs):
    #     super(BmimeasuremantForm,self).__init__(*args, **kwargs)
    #     self.fields['user'].empty_label = "Select"
    #     self.fields['user'].required = False

    # widgets = {
    #     'weight':forms.FloatField(attrs={'class':'form-control'}),
    #     'height':forms.FloatField(attrs={'class':'form-control'}),
    # }

bmi_app/views.py
from django.shortcuts import render, reverse, Http404, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from bmi_app.forms import BmimeasuremantForm
from bmi_app.models import BMIMeasurement, Suggestion
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from  django.template.loader import render_to_string



# Create your views here.

def bmi_list(request):
    bmimeasurements = BMIMeasurement.objects.filter(user=request.user)
    context = {"bmimeasurements":bmimeasurements}
    return render(request, 'bmi_list.html', context)


@login_required
def bmi_calculate(request):
    is_form_submitted = False
    bmi = None
    suggestion = None
    message  = None
    form = BmimeasuremantForm(request.POST or None)
    if form.is_valid():
        bmimeasurement=form.save(commit=False)
        bmimeasurement.user = request.user
        bmimeasurement.save()
        is_form_submitted = True
        bmi=bmimeasurement.bmi()
        if bmi <= 18.5:
            suggestion = "Underweight"
        elif bmi >= 18.6 and bmi <=24.9 :
            suggestion = "Normal weight"
        elif bmi > 25 and bmi < 29.9:
            suggestion = "Overweight"
        else:
            suggestion = "obsessed"
        message = suggestion

    context = {"form": form, "bmi": bmi, "is_form_submitted": is_form_submitted, "suggestion": suggestion, "message":message}
    return render(request, 'form.html', context)

def bmi_edit(request, id):
    bmimeasurement = get_object_or_404(BMIMeasurement, id=id)
    form = BmimeasuremantForm(request.POST or None, instance=bmimeasurement)
    if form.is_valid():
        form.save
        return HttpResponseRedirect(reverse("bmi_app:bmi_list"))
    context = {"form": form}
    return render(request, 'form.html', context)

def bmi_delete(request, id):
    bmimeasurement = get_object_or_404(BMIMeasurement, id=id)
    bmimeasurement.delete()
    return HttpResponseRedirect(reverse("bmi_app:bmi_list"))


def send_report(request):
    bmi = round(BMIMeasurement.bmi(BMIMeasurement.objects.all().last()),2)
    if bmi <= 18.5:
        message = "Underweight. You need to increase your weight"
    elif bmi >= 18.6 and bmi <=24.9:
        message = "Normal weight. You are fit and fine keep it up"
    elif bmi > 25 and bmi < 29.9:
        message = "Overweight. You need to reduce your weight"
    else:
        message = "obsessed. You are very overweight, please consult a doctor"
    send_mail(  "BMI report",
                message + " Your BMI is "+ str(bmi),
                "ytddash@gmail.com",
                # ["binod997243@gmail.com"],
                [request.user.profile.email],
                # false_silently = False
            )
    return render(request, "report.html",{})

bmi_app/templates/bmi_list.html
{% extends 'layout.html' %}
{% block title %}Details{% endblock title %}

{% block main_content %}
<section class="container">
    <div class="row justify-content-around text-center mt-5">
        <div class="col-sm-8">
            <h3>USER BMI CALCULATION LIST</h3>
        </div>
    </div>
    <div class="row justify-content-around mt-3">
        <div class="col-sm-12">
            <a href="{% url 'bmi_app:bmi_calculate' %}" class="btn btn-primary float-end">Add New</a>
        </div>
    </div>

    <div class="row justify-content-around text-center mt-1">
        <div class="col-sm-12">
            <table class="table table-dark table-hover">
                <thead class="border-bottom font-weight-bold">
            <tr>
                <th>User</th>
                <th>Weight</th>
                <th>Height</th>
                <th>Bmi</th>
                <th>Created</th>
                <th>Modified</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for bmimeasurement in bmimeasurements %}
                <tr>
                    <td>{{ bmimeasurement.user}}</td>
                    <td>
                        <a href="{% url 'bmi_app:bmi_edit' bmimeasurement.id %}">{{ bmimeasurement.weight }}</a>
                    </td>
                    <td>{{ bmimeasurement.height }}</td>
                    <td>{{ bmimeasurement.bmi|floatformat:2 }}</td>
                    <td>{{ bmimeasurement.created }}</td>
                    <td>{{ bmimeasurement.modified }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'bmi_app:bmi_delete' bmimeasurement.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
            </table>
        </div>
    </div>

</section>
{% endblock main_content %}

bmi_app/templates/form.html
{% extends 'layout.html' %}
{% block title %}Calculate{% endblock title %}
{% load crispy_forms_tags %}

{% block main_content %}

<div class="container">
    <div class="row justify-content-around mt-8">
        <div class="col-sm-6">
            <h3 class="text-white text-center">Calculate BMI</h3>
        </div>
    </div>
    <div class="row justify-content-around mt-3">
        <div class="col-sm-4">
            <form action="" method="post" class= 'bg-white p-3 rounded shadow'>
                {% csrf_token %}
                {% for form in form %}
                    {{form.label_tag}}
                    {{form.as_p}}
                    {{form}}
                {% endfor %}
                <br><input type="submit" value="Calculate" class="btn btn-primary my-2">
                <a class="btn btn-warning text-center" href="{% url 'bmi_app:send_report' %}" value="send mail">Send Mail </a>
            </form>
            {% if is_form_submitted %}
    {% if 18.5 >= bmi %}
    <h5 style="color:orange;"> Your Body Mass Index is {{bmi}}. This is considered {{suggestion}}. </h5>
    {% endif %}

    {% if bmi >= 18.6 and 24.9 >= bmi %}
    <h5 style="color:green;"> Your Body Mass Index is {{bmi}}. This is considered {{suggestion}}. </h5>
    {% endif %}

    {% if bmi >= 25 and 29.9 >= bmi %}
    <h5 style="color:blue;"> Your Body Mass Index is {{bmi}}. This is considered {{suggestion}}. </h5>
    {% endif %}

    {% if bmi >= 30 %}
    <h5 style="color:red;"> Your Body Mass Index is {{bmi}}. This is considered {{suggestion}}. </h5>
    {% endif %}

    {% if bmi <= 18.5 %}
        <h6>
            1)This indicates a lean BMI, which means you have a low amount of body fat. If you are an athlete, this can be desirable. If you are not an athlete, a lean BMI can indicate that your weight may be too low, which may lower your immunity. If your BMI and body weight are low, you should consider gaining weight through good diet and exercise habits, to increase your muscle mass.
        </h6>

    {% elif bmi >= 18.6 and bmi <= 24.9 %}
        <h6>
            1)You are fit and fine
        </h6>

    {% elif bmi >= 25 and bmi <= 29.9 %}
        <h6>
            1)This indicates an unhealthy condition, your excess mass is putting you at risk for heart disease, diabetes, high blood pressure, gall bladder disease, circulation problems, and some cancers. You should lose weight by changing your diet and exercising more.
        </h6>

    {% else %}
        <h6>
            1) Avoid fried and oily foods.<br>
            2) Avoid taking fats like butter,ghee because they increase the level of cholesterol in their blood.<br>
            3) Stop eating between meals.<br>
            4) Eating something all the time increases the calorie intake and thus increases weight.<br>
        </h6>
    {% endif %}
{% endif %}

        </div>
    </div>
</div>
{% endblock main_content %}

bmi_app/templates/report.html
<h1>Message Sent</h1>