BMI_Calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("bmi-app/", include("bmi_app.urls", namespace="bmi_app")),
    path("useraccount-app/", include("useraccount_app.urls", namespace="useraccount_app")),
]

bmi_app/urls.py
from django.urls import path
from bmi_app.views import bmi_list, bmi_calculate, bmi_edit, bmi_delete, send_report

app_name = "bmi_app"

urlpatterns = [
    path("bmi-list/", bmi_list, name="bmi_list"),
    path("bmi-calculate/", bmi_calculate, name="bmi_calculate"),
    path("bmi-edit/<int:id>/", bmi_edit, name="bmi_edit"),
    path("bmi-delete/<int:id>/", bmi_delete, name="bmi_delete"),
    path("send_report/", send_report, name="send_report"),
]

useraccount_app/urls.py
from django.urls import path
from useraccount_app.views import profile_list, profile_edit, UserLogin, signup_view, send_confirm_email
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from useraccount_app.forms import MyChangePasswordForm

app_name = "useraccount_app"

urlpatterns = [

    path("profile-list/", profile_list, name="profile_list"),
    path("profile-edit/<int:id>/", profile_edit, name="profile_edit"),
    path("login/", UserLogin.as_view(), name="login"),
    path("register/", signup_view, name="register"),
    path("send-mail/", send_confirm_email, name="send_mail"),
    path("logout/", LogoutView.as_view(next_page='/useraccount-app/login/'), name="logout"),
    path("change-password/", PasswordChangeView.as_view(template_name="change_password.html", form_class=MyChangePasswordForm), name="change_password"),
    path("password-change-done/", PasswordChangeDoneView.as_view(template_name="password_change_done.html"), name="password_change_done"),
]

useraccount_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    contact = models.CharField(max_length=255, null=True, blank=True)
    age = models.IntegerField(default=0)
    email = models.EmailField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

useraccount_app/forms.py
from django import forms
from useraccount_app.models import Profile
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User



class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class CustomSignupForm(UserCreationForm):
    email = forms.EmailField()
    # password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    # password2 = forms.CharField(label="Password Again", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    # widgets = {'username':forms.TextInput(attrs={'class':'form-control'})}
    # email = forms.CharField(required=True, widget=forms.EmailField(attrs={'class':'form-control'}))

class MyChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old password",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'autofocus': True, 'class':'form-control'}),
    )

    new_password1 = forms.CharField(
        label="New Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}),
    )

    new_password2 = forms.CharField(
        label="New Password Again",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}),
    )

useraccount_app/views.py
from django.shortcuts import render, reverse, Http404, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from useraccount_app.forms import ProfileForm
from django.contrib.auth.views import LoginView
from django.contrib import messages
from useraccount_app.models import Profile
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from useraccount_app.forms import CustomSignupForm
from django.contrib.auth import authenticate, login
from  django.template.loader import render_to_string
from django.core.mail import send_mail

# Create your views here.


def profile_list(request):
    profiles = Profile.objects.filter(user=request.user)
    context = {"profiles": profiles}
    print (context)
    return render(request, 'profile_list.html', context)


def profile_edit(request, id):
    profile = get_object_or_404(Profile, id=id)
    form = ProfileForm(request.POST or None, instance=profile)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("useraccount_app:profile_list"))
    context = {"form": form}
    return render(request, 'profile_form.html', context)


class UserLogin(LoginView):
    template_name = "login.html"
    redirect_authenticated_user = False


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = self.request.GET.get("next")
        return context

def signup_view(request):
    form = CustomSignupForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("useraccount_app:login"))
    context = {"form":form}
    return render(request, "register.html", context)

def send_confirm_email(request):
    subject = "Test Subject"
    message = "Test Meassage"
    from_email = "ytddash@gmail.com"
    recipient_list = ["binod997243@gmail.com"]
    context = {"name": "Binod"}
    html_message = render_to_string("user_profile.html")
    res = send_mail(subject, message, from_email,
    recipient_list, html_message=html_message)
    return HttpResponse(res)

useraccount_app/templates/change_password.html
{% extends 'layout.html' %}
{% block title %}Change Password{% endblock title %}

{% block main_content %}
    <section class="container">
        <div class="row justify-content-around mt-5">
            <div class="col-sm-5">
                <h3>Change Password</h3>
            </div>
        </div>
        <div class="row justify-content-around mt-2">
            <div class="col-sm-5">
                <form action="" method="post" class="bg-white p-3 rounded">
                    {% csrf_token %}
                    {% for form in form %}
                    {{form.label_tag}}
                    {{form}}
                    <small class="text-danger">{{form.errors|striptags}}</small>
                    {% endfor %}
                    <input type="submit" value="Change Password" class="btn btn-primary mt-2">
                </form>
            </div>
        </div>

    </section>

{% endblock main_content %}

useraccount_app/templates/login.html
{% extends 'layout.html' %}
{% block title %}Login{% endblock title %}

{% block main_content %}
<section class="container">
    <div class="row justify-content-around mt-5">
        <div class="col-md-5">
            <h3 class="text-white">Login Form</h3>
        </div>
    </div>
    <div class="row justify-content-around mt-3">
        <div class="col-md-4">
            <form action="" method="post" class="bg-white p-3 rounded shadow">
                {% csrf_token %}
                {% for form in form %}
                    {{form.label_tag}}
                    {{form.as_p}}
                    {{form}}
                    <small class="text-danger">{{form.errors}}</small>
                {% endfor %}
                <input type="submit" value="Login" class="btn btn-primary mt-2">
            </form>
        </div>
    </div>
</section>

{% endblock main_content %}

useraccount_app/templates/password_change_done.html
{% extends 'layout.html' %}
{% block title %}Password Change Done{% endblock title %}


{% block main_content %}
    <section class="container">
        <div class="row justify-content-around mt-5">
            <div class="col-sm-5 py-5 text-center rounded bg-white">
                <h3 class="text-success">Password Change Done</h3>
                <a href="http://" class="btn btn-danger mt-1">Home</a>
            </div>
        </div>

    </section>

{% endblock main_content %}

useraccount_app/templates/profile_form.html
{% extends 'layout.html' %}
{% block title %}Profile{% endblock title %}

{% block main_content %}
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}
    <input type="submit" name="submit", value="Submit" />
</form>

{% endblock main_content %}

useraccount_app/templates/profile_list.html
{% extends 'layout.html' %}
{% block title %}Details{% endblock title %}

{% block main_content %}
<section class="container">
    <div class="row justify-content-around text-center mt-5">
        <div class="col-sm-8">
            <h3>USER PROFILE </h3>
        </div>
    </div>

    <div class="row justify-content-around text-center mt-1">
        <div class="col-sm-12">
            <table class="table table-dark table-hover">
                <thead class="border-bottom font-weight-bold">
                    <tr>
                        <th>First_name</th>
                        <th>Last_name</th>
                        <th>Address</th>
                        <th>Contact</th>
                        <th>Age</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                </thead>
        <tbody>
            {% for profile in profiles %}
            <tr>
                <td>{{ profile.first_name }}</td>
                <td>{{ profile.last_name }}</td>
                <td>{{ profile.address }}</td>
                <td>{{ profile.contact }}</td>
                <td>{{ profile.age }}</td>
                <td>{{ profile.email }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'useraccount_app:profile_edit' profile.id %}">Edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
            </table>
        </div>
    </div>

</section>
{% endblock main_content %}

useraccount_app/templates/register.html
{% extends 'layout.html' %}
{% block title %}Sign Up{% endblock title %}

{% block main_content %}
<div class="container">
    <div class="row justify-content-around mt-5">
        <div class="col-sm-6">
            <h3 class="text-white text-center">Sign Up Form</h3>
        </div>
    </div>
    <div class="mt-3 row justify-content-around">
        <div class="col-sm-4">
            <form action="" method="post" class= 'bg-white p-3 rounded shadow'>
                {% csrf_token %}
                {% for form in form %}
                    {{form.label_tag}}
                    {{form.as_p}}
                    {{form}}
                    <small class="text-danger">{{form.errors|striptags}}</small>
                {% endfor %}
                <br><input type="submit" value="Submit" class="btn btn-primary my-2">
            </form>

        </div>
    </div>
</div>
{% endblock main_content %}

<form method="POST">
    {% csrf_token %}

</form>

useraccount_app/templates/test.html
<p style="color: red;">Calculate Your BMI, {{name}}</p>