BMI_Calculator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("bmi-app/", include("bmi_app.urls", namespace="bmi_app")),
    path("useraccount-app/", include("useraccount_app.urls", namespace="useraccount_app")),
]

bmi_app/urls.py
from django.urls import path
from bmi_app.views import bmi_list, bmi_calculate, bmi_edit, bmi_delete, send_report

app_name = "bmi_app"

urlpatterns = [
    path("bmi-list/", bmi_list, name="bmi_list"),
    path("bmi-calculate/", bmi_calculate, name="bmi_calculate"),
    path("bmi-edit/<int:id>/", bmi_edit, name="bmi_edit"),
    path("bmi-delete/<int:id>/", bmi_delete, name="bmi_delete"),
    path("send_report/", send_report, name="send_report"),
]

useraccount_app/urls.py
from django.urls import path
from useraccount_app.views import profile_list, profile_edit, UserLogin, signup_view, send_confirm_email
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from useraccount_app.forms import MyChangePasswordForm

app_name = "useraccount_app"

urlpatterns = [

    path("profile-list/", profile_list, name="profile_list"),
    path("profile-edit/<int:id>/", profile_edit, name="profile_edit"),
    path("login/", UserLogin.as_view(), name="login"),
    path("register/", signup_view, name="register"),
    path("send-mail/", send_confirm_email, name="send_mail"),
    path("logout/", LogoutView.as_view(next_page='/useraccount-app/login/'), name="logout"),
    path("change-password/", PasswordChangeView.as_view(template_name="change_password.html", form_class=MyChangePasswordForm), name="change_password"),
    path("password-change-done/", PasswordChangeDoneView.as_view(template_name="password_change_done.html"), name="password_change_done"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{title}}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h2 class="display-4">BMI Calculation</h2>
                <hr class="my-4">
                {% block navbar %}
                {% endblock navbar %}
                {% block content %}
                    <p>This is base file.</p>
                {% endblock content %}
            </div>
        </div>

    </body>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</html>

templates/layout.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <title>{% block title %}{% endblock title %} | BMI</title>
</head>

<body>
    {% include 'navbar.html' %}
    {% block main_content %}{% endblock main_content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
    {% block myscript %}{% endblock myscript %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <!-- <a class="navbar-brand" href="#">Bmi Calculator</a> -->
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul> -->
            <ul class="navbar-nav  mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <!-- <a class="nav-link" href="{% url 'useraccount_app:profile_list' %}">{{request.user}}</a> -->
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{request.user}}
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'useraccount_app:profile_list' %}">{{request.user}}</a></li>
                            <li><a class="dropdown-item" href="{% url 'useraccount_app:change_password' %}">Change Password</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'useraccount_app:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'useraccount_app:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'useraccount_app:register' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>